// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgenciaViajes.Domain.Entities;

public partial class Agente
{
    public int IdAgente { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string CorreoElectronico { get; set; }

    public string Contraseña { get; set; }

    public string Telefono { get; set; }

    public string DocumentoIdentidad { get; set; }

    public DateTime FechaRegistro { get; set; }

    public string CodigoAgente { get; set; }

    public string Estado { get; set; }

    public virtual ICollection<Hotel> Hoteles { get; set; } = new List<Hotel>();
}