// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgenciaViajes.Domain.Entities;

public partial class Ciudad
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<Hotel> Hoteles { get; set; } = new List<Hotel>();
}