// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgenciaViajes.Domain.Entities;

public partial class ComisionReserva
{
    public int IdComision { get; set; }

    public int IdReserva { get; set; }

    public decimal MontoBaseReserva { get; set; }

    public decimal PorcentajeComision { get; set; }

    public decimal MontoComision { get; set; }

    public DateTime? FechaCalculo { get; set; }

    public string Estado { get; set; }

    public virtual Reserva Reserva { get; set; }

    public decimal ObtenerMontoComision()
    {
        return MontoBaseReserva * PorcentajeComision;
    }
}