// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgenciaViajes.Domain.Entities;

public partial class DetalleReserva
{
    public int IdDetalleReserva { get; set; }

    public int IdReserva { get; set; }

    public string Concepto { get; set; }

    public int Cantidad { get; set; }

    public decimal PrecioUnitario { get; set; }

    public decimal Importe { get; set; }

    public virtual Reserva Reserva { get; set; }

    public decimal ObtenerImporte()
    {
        return Cantidad * PrecioUnitario;
    }
}