// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgenciaViajes.Domain.Entities;

public partial class Habitacion
{
    public int IdHabitacion { get; set; }

    public int IdHotel { get; set; }

    public int IdTipoHabitacion { get; set; }

    public decimal CostoBase { get; set; }

    public decimal Impuestos { get; set; }

    public int CantidadHuespedes { get; set; }

    public string Ubicacion { get; set; }

    public string Estado { get; set; }

    public virtual Hotel Hotel { get; set; }

    public virtual TipoHabitacion TipoHabitacion { get; set; }

    public virtual ICollection<Reserva> Reservas { get; set; } = new List<Reserva>();

    public void Habilitar()
    {
        Estado = "Habilitada";
    }

    public void Desabilitar() 
    {
        Estado = "Desabilitada";
    }
}