// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgenciaViajes.Domain.Entities;

public partial class Habitacion
{
    public int IdHabitacion { get; private set; }

    public int IdHotel { get; private set; }

    public int IdTipoHabitacion { get; private set; }

    public decimal CostoBase { get; private set; }

    public decimal Impuestos { get; private set; }

    public int CantidadHuespedes { get; private set; }

    public string Ubicacion { get; private set; }

    public string Estado { get; private set; }

    public virtual Hotel Hotel { get; private set; }

    public virtual TipoHabitacion TipoHabitacion { get; private set; }

    public virtual ICollection<Reserva> Reservas { get; private set; } = new List<Reserva>();

    public Habitacion() {}

    private Habitacion(
        Hotel hotel,
        TipoHabitacion tipoHabitacion,
        decimal costoBase,
        decimal impuestos,
        int cantidadHuespedes,
        string ubicacion)
    {
        Hotel = hotel;
        TipoHabitacion = tipoHabitacion;
        CostoBase = costoBase;
        Impuestos = impuestos;
        CantidadHuespedes = cantidadHuespedes;
        Ubicacion = ubicacion;
    }

    public static Habitacion Crear(
        Hotel hotel,
        TipoHabitacion tipoHabitacion,
        decimal costoBase,
        decimal impuestos,
        int cantidadHuespedes,
        string ubicacion)
    {
        var habitacion = new Habitacion(
            hotel,
            tipoHabitacion,
            costoBase,
            impuestos,
            cantidadHuespedes,
            ubicacion
        );

        return habitacion;
    }

    public void Habilitar()
    {
        Estado = "Habilitada";
    }

    public void Desabilitar() 
    {
        Estado = "Desabilitada";
    }
}