// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgenciaViajes.Domain.Entities;

public partial class Hotel
{
    public int IdHotel { get; set; }

    public int IdAgente { get; set; }

    public int IdCiudad { get; set; }

    public string Nombre { get; set; }

    public string Direccion { get; set; }

    public string Descripcion { get; set; }

    public string Estado { get; set; }

    public virtual ICollection<Habitacion> Habitaciones { get; set; } = new List<Habitacion>();

    public virtual Agente Agente { get; set; }

    public virtual Ciudad Ciudad { get; set; }

    public void Habilitar()
    {
        Estado = "habilitado";
    }

    public void Desabilitar()
    {
        Estado = "desabilitado";
    }
}