// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgenciaViajes.Domain.Entities;

public partial class Huesped
{
    public int IdHuesped { get; set; }

    public int IdTipoDocumento { get; set; }

    public int IdGenero { get; set; }

    public string Nombres { get; set; }

    public string Apellidos { get; set; }

    public DateOnly FechaNacimiento { get; set; }

    public string NumeroDocumento { get; set; }

    public string CorreoElectronico { get; set; }

    public string Contraseña { get; set; }

    public string Telefono { get; set; }

    public virtual Genero Genero { get; set; }

    public virtual TipoDocumento TipoDocumento { get; set; }

    public virtual ICollection<Reserva> Reservas { get; set; } = new List<Reserva>();
}