// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgenciaViajes.Domain.Entities;

public partial class Huesped
{
    public int IdHuesped { get; private set; }

    public int IdTipoDocumento { get; private set; }

    public int IdGenero { get; private set; }

    public string Nombres { get; private set; }

    public string Apellidos { get; private set; }

    public DateOnly FechaNacimiento { get; private set; }

    public string NumeroDocumento { get; private set; }

    public string CorreoElectronico { get; private set; }

    public string Contraseña { get; private set; }

    public string Telefono { get; private set; }

    public virtual Genero Genero { get; private set; }

    public virtual TipoDocumento TipoDocumento { get; private set; }

    public virtual ICollection<Reserva> Reservas { get; private set; } = new List<Reserva>();

    public Huesped() {}

    private Huesped(
        Genero genero,
        TipoDocumento tipoDocumento,
        string nombres,
        string apellidos,
        DateOnly fechaNacimiento,
        string numeroDocumento,
        string correoElectronico,
        string contraseña,
        string telefono)
    {
        Genero = genero;
        TipoDocumento = tipoDocumento;
        Nombres = nombres;
        Apellidos = apellidos;
        FechaNacimiento = fechaNacimiento;
        NumeroDocumento = numeroDocumento;
        CorreoElectronico = correoElectronico;
        Contraseña = contraseña;
        Telefono = telefono;
    }

    public static Huesped Crear(
        Genero genero,
        TipoDocumento tipoDocumento,
        string nombres,
        string apellidos,
        DateOnly fechaNacimiento,
        string numeroDocumento,
        string correoElectronico,
        string contraseña,
        string telefono)
    {
        var huesped = new Huesped(
            genero,
            tipoDocumento,
            nombres,
            apellidos,
            fechaNacimiento,
            numeroDocumento,
            correoElectronico,
            contraseña,
            telefono
        );

        return huesped;
    }
}