// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgenciaViajes.Domain.Entities;

public partial class Reserva
{
    public int IdReserva { get; set; }

    public int IdHuesped { get; set; }

    public int IdHabitacion { get; set; }

    public DateTime FechaReserva { get; set; }

    public DateTime FechaIngreso { get; set; }

    public DateTime FechaSalida { get; set; }

    public string ContactoEmergencia { get; set; }

    public decimal Subtotal { get; set; }

    public decimal Iva { get; set; }

    public decimal Total { get; set; }

    public string Estado { get; set; }

    public virtual ICollection<ComisionReserva> ComisionReservas { get; set; } = new List<ComisionReserva>();

    public virtual ICollection<DetalleReserva> DetalleReservas { get; set; } = new List<DetalleReserva>();

    public virtual Habitacion Habitacion { get; set; }

    public virtual Huesped Huesped { get; set; }

    public decimal ObtenerSubtotal()
    {
        return DetalleReservas.Sum(x => x.Importe);
    }

    public decimal ObtenerTotal()
    {
        return DetalleReservas.Sum(x => x.Importe + ( x.Importe * 0.19m ));
    }
}